### ISSUE TITLE
visibleXRangeMaximum not refreshing

### ISSUE THREAD

**Issue by 128keaton** [danielgindi/Charts#1037]
Ok, interesting problem, I'll have three data points on one chart mode. I'll change the mode to a 'tighter view' (removing the last data point, my chart has 6/12/24 hour modes of data) and then go back to the previous view, but the last data point is cut off.
The count is correct, I've checked

`self.insulinChart?.setVisibleXRangeMaximum(CGFloat(bgVals.count))`

It will report 3, but only show two points

And, I really hate creating issues here. It really is a superb library!

**Comment by liuxuan30** [comment]
Usually a new user that heavily has strong requirement on chart will ask issues :)
I suggest you walk through the code and debug on your side, and you are more than welcome to fix it.

Now back to the issue:
is it possible to reproduce with ChartsDemo? 
I would suggest you go to the chart renderer's `drawDataSet` func, to see why the last point is ignored. 
I'm not sure if this is because the matrix is wrong so the point will not be drawn, or the last point is really out of the rect

**Comment by 128keaton** [comment]
@liuxuan30 I did disable horizontal scrolling, because I have a swipe gesture. However, if I relaunch the application, the third point is rendered perfectly.

**Comment by liuxuan30** [comment]
@128keaton I would definitely suggest you grab a cup of tea and walk through the code :) You are close to the answer, but I don't have your env to help you debug.

**Comment by 128keaton** [comment]
I'd still like a solution. I've searched and searched, to no avail.
