### ISSUE TITLE
The horizontal line that forms the grid of the LineChartView are not the same color 

### ISSUE THREAD

**Issue by daisoreanu** [danielgindi/Charts#1051]
Hi and thank you in advance for any support,

My issue is that I don't seem to be able to change the yAxis grid properties for the LineChartView, so that it can make the color of the line into lightGray. The issue is that the original grid lines are not the same color, as some of them appear with different alphas or something like that...

Please check the photo for more detail:
[chart picture](https://www.dropbox.com/s/0lk9wnqo8zktpz7/LineChartView%20yAxis.png?dl=0)

**Comment by liuxuan30** [comment]
I don't know why I can't see your image while I can google..

**Comment by daisoreanu** [comment]
not sure I understand, maybe you have a chrome issue of some sort...

**Comment by daisoreanu** [comment]
Also is there a way to add only a one transparent circle maybe using circleRadius or setCircleColor from the class LineChartDataSet

**Comment by liuxuan30** [comment]
I see your image now. Have you changed anything about the grid line? Normally it won't be such cases. They will be same color I surpose. Did you see it on ChartsDemo?

To your second question, if you have any custom requirements, you will need to take a look at the code about how the circle is drawn(in drawCircles of line chart renderer), and see if current properties can meet your demand, or you have to slightly change some code.

**Comment by danielgindi** [comment]
You have a scaling issue.
If you're watching it in iPhone Simulator, then please make sure you're in 100% zoom.
Otherwise, make sure that your app is configured for 100% scale, 1:1 with device logical pixels. This is achieved by having correct `Default___.png` for the device. For iPhone 6+, have a `Default@3x.png` in the correct size.
If you are on iPhone 6+, and don't have a correct `Default.png` (either in a file or in Assets), then the iPhone scales it up - and you get weird alpha issues.
