### ISSUE TITLE
BUG::: leftAxis.axisMinValue !!!=== 0.0 

### ISSUE THREAD

**Issue by dsencheng** [danielgindi/Charts#1101]
![qq20160602-0 2x](https://cloud.githubusercontent.com/assets/4113331/15732511/5d3074b0-28b0-11e6-9c6e-0bf6104b5f05.png)

**Comment by liuxuan30** [comment]
Please be more specific how this happens in your first three charts. Usually you should see it's fine. Have you call notifyDataSetChanged after you set leftAxis.axisMinValue?

**Comment by dsencheng** [comment]
@liuxuan30 可以中文描述么？ 在BarChartViewController.m 75行 注释掉leftAxis.axisMinValue = 0.0，然后运行，每次出现的底部高度不一样。预期的是一直在X轴上。
BarChartViewController - Line 75 
push..pop..push..pop..push..pop
Not the same result

**Comment by liuxuan30** [comment]
@dsencheng I encourage you use English, because more people can help you. I have added a translation.

Now back to the topic: I'm not sure if this is a bug or not.

By default, if you do nothing, the y axis range is calculated via y axis renderer's `computeAxisValues`, it takes yMin and yMax as arguments. In ChartYAxis, `calculate` is calculating _axisMinimum, which is yMin later.

Now in your case, you let the library to calculate y axis range for you, so it will goes to:
```swift
        // bottom-space only effects non-custom min
        if !_customAxisMin
        {
            let bottomSpace = range * Double(spaceBottom)
            _axisMinimum = min - bottomSpace
        }
```
and axisMinimum is a small negative now. So, if you want to always starts from zero, you should explicitly call `leftAxis.axisMinValue = 0.0`

**Comment by dsencheng** [comment]
@liuxuan30  抱歉，英文实在不好。我还是用中文描述下好了。这个问题是柱状图底部不在X轴上，它偏移了。我希望柱状图固定在X轴上，并且我不需要设置axisMinValue = 0.0

**Comment by liuxuan30** [comment]
if you want to make bar stay right on x axis, you have to set axisMinValue = 0.0
