### ISSUE TITLE
Using prebuilt frameworks is not recommended

### ISSUE THREAD

**Issue by eshurakov** [danielgindi/Charts#1118]
As mentioned in https://developer.apple.com/swift/blog/?id=2 binary frameworks written in swift should be compiled using the same version of Xcode and swift compiler to ensure compatibility.

Carthage fetches binary frameworks by default, which could potentially lead to compilation errors or difficult to track runtime issues.

Because of this I think it would be best to remove the binaries from release page.

**Comment by ahknight** [comment]
Or add it as a "git" dependency, which forces a clone and build.

**Comment by liuxuan30** [comment]
I am not sure if it's worthy to do this.. as the blog said after Swift stabilized, it will part of the OS, so the issues are gone. Swift 3.0 seems the time?

**Comment by liuxuan30** [comment]
oops, seems being part of OS is no longer happening for swift 3.0:http://ericasadun.com/2016/05/16/winding-down-swift-3-0-abi-stability-deferred/

**Comment by danielgindi** [comment]
@petester42 do you think we should avoid adding precompiled binaries in the next releases?

**Comment by petester42** [comment]
I really think we should. It causes nothing but headaches for developers. So far when there has been a new version of swift you need to create a new prebuilt framework even if the source doesn't need to change. 

When I was using Carthage I always would pass in the "don't download binaries" because of the issue mentioned above. 

Also Apple and the community seem to agree that it's a bad idea right now.

**Comment by danielgindi** [comment]
I've removed the precompiled binaries from all current releases.
Now I just need to remove the Realm compiled framework from the project...
