### ISSUE TITLE
How to handle small interval

### ISSUE THREAD

**Issue by ziadtamim** [danielgindi/Charts#1147]
Great library!!

I would like to know if there is a way to decline line chart to make it obvious between values as I have just  small intervals between.

![screen shot 2016-06-16 at 1 25 42 am](https://cloud.githubusercontent.com/assets/1026099/16102684/ac446f98-3369-11e6-9048-34f4de04f531.png)

**Comment by liuxuan30** [comment]
Could you explain it? I can't understand the question and the screenshot

**Comment by ziadtamim** [comment]
The issue here is you can't notice the difference on the chart because of the values are so close to each other with a tiny difference.

The values are as follow: 

> 190, 189, 188, 187, 186

![ac446f98-3369-11e6-9048-34f4de04f531](https://cloud.githubusercontent.com/assets/1026099/16125568/219163aa-33ec-11e6-9be3-d362d8c7c9df.png)

**Comment by liuxuan30** [comment]
I am asking because, I don't see what "tiny difference" means, you had the data, and it draws lines. Though I don't see a more obvious line, but I see you fill it.

If you are saying the y axis range, simply not started from zero (if you are), so the range may be calculated such as [170, 180 190, 200]

**Comment by danielgindi** [comment]
You can take your values further apart ;-) Or you can have an actual line. Right now it seems you only have a fill.
