### ISSUE TITLE
can we implement group bar chart and line chart as combined chart

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1184]
hey, i am trying to implement combined chart with group bar chart and line chart group bar chart get misplaced in chart can anyone help me.
How to implement group bar chart and line chart as combined chart in swift?

**Comment by liuxuan30** [comment]
@PhilJay is working on this I suppose and target for 3.0 release. So please be pacient, it's not easy to do so as we have to think cross platform, and other stuff.

I had #269 to do this just for iOS, you could try it out. I don't sync it with amster for a while, since I think #269 will be closed once 3.0 is released, as they are having their own way to implement than mine
