### ISSUE TITLE
addEntryOrdered behavior - clarification

### ISSUE THREAD

**Issue by popaaaandrei** [danielgindi/Charts#1242]
Dear All,

First of all, thank you for putting the effort, the library is super-cool.

My problem is data-related. I need to be able to insert entries at custom X locations so I tried using `addEntryOrdered`. This is what happens when I try to insert at index 1, value 62. From the name, I was expecting a linked-list like behavior, but it seems that the entries are not redistributed.

<img width="366" alt="screen shot 2016-07-12 at 09 10 21" src="https://cloud.githubusercontent.com/assets/14068535/16756848/84e41cb2-4810-11e6-9b3e-71f66a01308f.png">

**First question**: is this the desired behavior or am I missing something?
Right now, the only way I was able to achieve this is to reset data/set entirely at every entry insert operation. I didn't find any move / redistribute call.

**Second question:** does every `addEntry / addEntryOrdered` need to be paired with a corresponding `data.addXValue` call?

Thank you!
Andrei

**Comment by danielgindi** [comment]
Data should `always` be ordered. Otherwise, the library cannot know that it reached an out-of-view x value, and will evaluate every possible x for whether it needs to be rendered.

`addEntry` means you know that the order is correct - and the library can avoid searching for the correct position in the array to add it.
`addEntryOrderer` looks for the position in the array to add it to.

The ordering is **on the x axis only**. A higher Y value can logically still appear before a lower one.

`addXValue` should be called for x-indices which did not exist before... Anyway in Charts 3.0 this concept has gone away.
