### ISSUE TITLE
Hide specific labels on y axis

### ISSUE THREAD

**Issue by jayesh15111988** [danielgindi/Charts#1253]
I was looking for a way to hide specific labels on the y axis. I have a y axis values ranging from 0-100. I don't want to show the zero value at all. At the same time I was to make it looks like as if zero value were there. Any help is much appreciated.

**Comment by mancunianetz** [comment]
I've had similar issue these days and had to modify the framework's source code. What I did is added in `ChartYAxis` class a bool value, in your case could be `hideFirstValue`, then in `ChartYAxisRenderer` modify `drawYLabels` method, serch for `for i in 0 ..< yAxis.entryCount` code, inside of `for` statment check if `i == 0` then just bypass current iteration using `continue`, this way it won't add label for first value.

```
for i in 0 ..< yAxis.entryCount {

   if i == 0 {
        continue
   }

  // the rest of the code
}
```

Of course instead of bool value you can add an index, would be more flexible to hide any label you want.

**Comment by jayesh15111988** [comment]
@mancunianetz I just used `chart.leftAxis.startAtZeroEnabled = NO` to suppress the zero value at the beginning.
