### ISSUE TITLE
Charts vs. ShinobiCharts?

### ISSUE THREAD

**Issue by marbetschar** [danielgindi/Charts#1259]
I'm currently struggling in the decusion between ShinobiCharts and you're Chart framework.

What are the pros/cons of both in comparison?
Apart from price and the fact that Charts runs also on macOS I can't find any major difference.

So I tend to believe that performance wies Charts isn't as fast as ShinobiCharts and it may also be less configurable / beautifull...?

I would really prefer to use Charts, but because of the lack of a direct comparison choosing ShinobiCharts feels like the save route.

Sorry if this is off topic here on GitHub but I couldn't figure out where to ask.

**Comment by liuxuan30** [comment]
well, I failed to try shinobi charts last year, so I don't know the features in shinobi chart and the advantages and how they implemented.

I think the short answer is, if you are personal user, Charts is better. If you are using library in commercial case, you should talk to your product manager knowing the requirements, and road maps, etc.

As you may know, different people have different demands for 'chart', like the colors, shapes, animations.. etc. From my experience, what you should consider first is, what framework *right now* meets your requirements, simply because your work depends on it and you have to do it *right now*. If your chart is going to change, like one day product manager wants you to implement something that shinobi charts does not have but Charts has, and vice-versa.

I would say Charts has a lot of space to improve, and authors and other people are improving it, however this is free software, so you can't push anyone to implement something for you. The pros is you have the code and you can do whatever you like, the cons is, you have to do it yourself.. or wait (lol). I don't know if shinobi chart can provide you code or customizations for customers.

Speaking of performance, I would say when you have huge data (~500 entries in combined chart), the animation is lagging, due to the fact it is built on pure CoreGraphics, and everything is redrawing when highlighting or interacting with the chart. I think this can be improved, but it seems long way to go.

So in simple words, I believe Charts is highly flexible in if you understand the details (you can even create new chart type using the APIs), but the animation and performance is something you should be careful when comparing.
