### ISSUE TITLE
text value on the last entry is missing from line chart

### ISSUE THREAD

**Issue by kennycoding** [danielgindi/Charts#1323]
repro: run the ios demo, show the first line chart, notice that the value (text) on the last entry is missing, although the value point is drawn.

**Comment by kennycoding** [comment]
my current work around is to add a dummy entry with same value as the last

**Comment by danielgindi** [comment]
On what version of Charts?

**Comment by kennycoding** [comment]
version 2.2.5, build 21

**Comment by danielgindi** [comment]
Did you try on 3.0?

**Comment by spinosa** [comment]
@danielgindi this is still happening on 3.0 as of https://github.com/danielgindi/Charts/commit/55405033684cda362ba2a1b839335dd8b3ba5395 (latest code as of right now; September 28th).

Run the demo.  See the last data point drawn without a label:

<img width="321" alt="screen shot 2016-09-28 at 12 41 07 pm" src="https://cloud.githubusercontent.com/assets/68957/18923064/faecfadc-8578-11e6-8778-e9ea4674c0c9.png">

It seems `drawValues(context:)` may not be calculating `stride` correctly (`LineChartRenderer.swift:552`).

**Comment by liuxuan30** [comment]
I tried to fix it by changing `to` to `through` in 
```swift
for j in stride(from: _xBounds.min, to: Int(ceil(Double(_xBounds.max - _xBounds.min) * phaseX + Double(_xBounds.min))), by: 1)
```
This did fix the missing label, however, I found a new issue that when zoomed in, and the animation on x axis is not in sync: the value  text will jump out first and then come with the line. Changing back to `to` the animation will be good. Weird...

**Comment by ryanschneider** [comment]
Sorry, didn't see this issue before opening #1585 and the #1586 PR.  I'll keep my comments here, but will leave it up to you guys on if you want to close those.

Anyways, what about adjusting the stride based on `phaseX`?

In pseudo-code:

```swift
open override func drawValues(context: CGContext) {
    ///snip
    let isAnimatingX = phaseX != 1.0
    let through = isAnimatingX ?
        Int(ceil(Double(_xBounds.max - _xBounds.min) * phaseX + Double(_xBounds.min))) - 1 :
        Int(ceil(Double(_xBounds.max - _xBounds.min) * phaseX + Double(_xBounds.min)))

    for j in stride(from: _xBounds.min, through: through, by: 1) {

    }
    ///snip
}
```

I think that resolves the issue, but some comments or rationale on the equation used to calculate the to/through value would be helpful.  That equation is pretty dense so personally I'd prefer to see it broken down into separate lines or a helper function on XBounds (`maxVisibleValue(forPhaseX:)` or something like that).

**Comment by ryanschneider** [comment]
Hmm, actually, after playing with the above code in the `ChartsDemo`, I think the issue is actually  related to `XBounds`.  

In both `master` and the code above, there's a completely separate issue in the animation where the last value *pops* in much later than the other ones.

This is very easy to see if you use the "Animate XY" option in the demo app Line Chart with the above code change.

I probably won't get much more time to look at it today, but my guess is there's something subtly wrong in `XBounds.set(...)`, and that if that was fixed it would work for both drawValues and the other drawing functions for circles and lines.

**Comment by liuxuan30** [comment]
I agree, it's different issue. However, I am not able to fine where the lag happens..

**Comment by ryanschneider** [comment]
FWIW I've been using the proposed fix:

```swift
for j in stride(from: _xBounds.min, to: Int(ceil(Double(_xBounds.max - _xBounds.min) * phaseX + Double(_xBounds.min))), by: 1)
```

In our app.  However, there seems to be an edge case that's not handled now, as we are getting some crashes on the next line:

```swift
guard let e = dataSet.entryForIndex(j) else { break }
```

Symbolication seem to be completely broken in iOS XCode 8, so I'm having to do this manually, but the crash looks to be because `j` is out of bounds for `_value` in `entryForIndex`.  If I manually run `symbols /path/to/My.app/Frameworks/Charts.framework/Charts` then work back through the addresses in the crash log, I get:

```
- 0x000000000005c7f8 (    0x30) specialized Array._checkSubscript(Int, wasNativeTypeChecked : Bool) -> _DependenceToken [FUNC, PEXT, NameNList, MangledNameNList, Merge
d, NList, FunctionStarts]
- 0x000000000005ac64 (   0x104) ChartDataSet.entryForXValue(Double, rounding : ChartDataSetRounding) -> ChartDataEntry? [FUNC, EXT, NameNList, MangledNameNList, Merged
, NList, FunctionStarts]
- 0x00000000000ac0ac (   0xd70) specialized LineChartRenderer.drawValues(context : CGContext) -> () [FUNC, EXT, LENGTH, NameNList, MangledNameNList, Merged, NList, Dwa
rf, FunctionStarts]
```

I'm still not sure if the root cause is in `XBounds` or the "ceil * phase" mapping to a value in the `through:` argument, just wanted to leave this here so people know this fix has potential issues.
