### ISSUE TITLE
Grouped Bar Charts 

### ISSUE THREAD

**Issue by narri007** [danielgindi/Charts#1333]
Hi, I am using Bar charts in my project. 
Now I want to implement grouped charts with two different scales. On left axis the scale should be based on **dataSet1** , on right axis the  scale should be based on **dataSet2**. How can I achieve this? Below is the required output screen. 
![activity](https://cloud.githubusercontent.com/assets/5907338/17770809/55a098bc-655d-11e6-9cc9-a2ba4ed47f6e.png)

Thanks in advance!

**Comment by liuxuan30** [comment]
@danielgindi I remember we did not support this in v3 right?

**Comment by narri007** [comment]
Can you please suggest me any way to achieve this.

**Comment by danielgindi** [comment]
Actually you can do this. You just have to calculate the grouped bar positions yourself. You can take a look the the built-in function that calculates the positions.

What you want to achieve is to offset the second bar by `(- barWidth / 2.0 )`, or offset the first one by `(barWidth / 4.0 )` and the second one by `(- barWidth / 4.0 )`

This is possible due to the fact that you can specify any x-value you like!

**Comment by liuxuan30** [comment]
guess we can document somewhere. It's valuable.
