### ISSUE TITLE
Chart's X-axis labels not resizing to accommodate multi-line text

### ISSUE THREAD

**Issue by mdhornet90** [danielgindi/Charts#1352]
I have enabled word wrap and I'm attempting to display a label in the form "Jun 13", where "Jun" is on the first line, "13" on the second. With wordWrapWidthPercent set to 2.0, these are the results:

![image](https://cloud.githubusercontent.com/assets/424092/17942156/1388630a-69eb-11e6-8592-4f2b829df00e.png)

If you're wondering why I didn't use the default widthPercent, it cuts the label down to just "Ju".

Is there something I'm not configuring properly? I assume the labels should just be sizing themselves.

ADDITIONAL INFO:
I'm consuming this via CocoaPods, version 2.2.5

**Comment by danielgindi** [comment]
Please try to add extra offset for the chart, at the bottom.

I think that what you are experiencing is the inability to properly assess the expected label's height, due to the current way of calculating average length, for performance. This might change in the future.

Anyway, the labels may be drawing but out of bounds, so just add an `extraBottomOffset` for the meantime.
