### ISSUE TITLE
rightAxis labels are not showing for value less then 1.0 in swift using cocoapod

### ISSUE THREAD

**Issue by fazal07** [danielgindi/Charts#1354]
![simulator screen shot 25-aug-2016 11 45 35 am](https://cloud.githubusercontent.com/assets/15004771/17959406/a20186ce-6ab9-11e6-8a82-d98dc217270a.png)

**Comment by danielgindi** [comment]
They do show, it just that you do not show enough of the Y axis.
Notice that the labels above 0.0 do not show as well.
That's because all your values are between 0.0 and 0.6, while the grid line intervals are larger.
You can control this with granularity. If I'm not mistaken - it's default value is 1.0, so there won't be grid lines/labels below intervals of 1.0 value.
