### ISSUE TITLE
PieChart, not show zero Label

### ISSUE THREAD

**Issue by araujotadeu** [danielgindi/Charts#1395]
When I am creating a PieChart and one or more of the values are zero, inside the graph the zero is printed, to this case I don't want the label inside the the chart be printed.

Taking a look in the render of the chart ( the Pie part ), it is validate to only print values bigger than zero, I think the same rule should be applied to the label too.
Example:

![img_0053a](https://cloud.githubusercontent.com/assets/9177950/18256556/3b200110-738d-11e6-826f-707a6e7a3546.PNG)

**Comment by iAviatorJose** [comment]
@araujotadeu  even i am facing these issue, have you found the solution for the same.

**Comment by araujotadeu** [comment]
@iAviatorJose for the moment what I did was fork the project and create a custom version of the 2.2.5 version, fixing ( or maybe changing the behaviour ) this. I looked the source code, the renderer of the chart before draw a section of the chart check if the value is bigger than 0, so I did the same validation when the label is rendered. I particularly believe that this behaviour can be considered an issue, or at least when could have a property like "renderZeroLabel" (boolean) to parametrise this behaviour.

**Comment by danielgindi** [comment]
I'm not sure that labels should not be rendered if the value is zero. The sections are skipped because they caused glitches on both iOS and Android.
But your screenshot actually looks great! Some people may want to see that "0" on the pie.

What you could very easily do, is use your formatter to return an empty string for the label of this value.
If you're still on Charts 2.2.5, please consider trying Charts 3.0, this helps us get it to release faster as people are finding bugs :-)

**Comment by araujotadeu** [comment]
@danielgindi thanks for the help, I agree that some people may want to see the "0", unfortunately in my case the PO don't. By I particularly don't like to pass a empty string too, sounds like a "quick fix", I believe a real solution could by this be parametrised.

About the Charts version, we will update soon.

**Comment by MuRanJiangXia** [comment]
hello,I don't want to display the pie chart by zero percent. How can I do this
![2018-12-20 3 45 58](https://user-images.githubusercontent.com/24642593/50271677-69d62180-0470-11e9-9ad3-ccb866b55202.png)
