### ISSUE TITLE
Getting error, while assigning xVals to PieChartData. 

### ISSUE THREAD

**Issue by nhkrishna5** [danielgindi/Charts#1433]
I am using Xcode 7.3 and swift 2.2.

![screen shot 2016-09-13 at 11 50 49 am](https://cloud.githubusercontent.com/assets/8044870/18463520/6bc2a73e-79a8-11e6-88de-bfcba0cc2609.png)

**Comment by wirasetiawan29** [comment]
ya I got same error, it's look like PieChartData.swift only have one parameter. 
Did it's a new update??

**Comment by nhkrishna5** [comment]
ya, i am  using latest code.

**Comment by petester42** [comment]
If you are using 3.0 all Data objects only take a dataset. See #1474 for all changes.

**Comment by leszarna** [comment]
I think people often go from google straight here. It would seem much better to answer ticket with 2 line example than to write answers like go to #1474. Most people doesn't use this library much, and searching some changelog is simply waste of time. It's not easy to find solution in 15 minutes for me so probably same for others.

**Comment by petester42** [comment]
Well if that is the case we welcome you to help improve the documentation. I think that looking at the demo and stuff should more than enough to figure out how to use the library for basic use cases. I can't spend my time writing code for others, I will point someone in the right direction and hope they find their answers or wait for them to ask more follow questions so that I can help them find answers they seek.
