### ISSUE TITLE
Marker display is abnormal

### ISSUE THREAD

**Issue by Sun-Hong** [danielgindi/Charts#1575]
In the bar chart, if you click on the last few columns, the bubble will appear in a position offset where it should be.
 If I change BalloonMarker.swift in the 63rd line of `code x: point.x + offset.x,` as `x: point.x,`, it shows normal.<br>
![bug](https://cloud.githubusercontent.com/assets/14048658/18909330/c0e91ce4-85a5-11e6-96b2-1200b8498a94.png)

**Comment by liuxuan30** [comment]
Chart version?

**Comment by danielgindi** [comment]
It's actually not a bug, but a feature, as they say...
Instead of the marker being cut by the view, it is offset to stay in the view. This behavior can be enabled/disabled/customized by any custom marker.
This specific marker is simplistic, and the arrow does not move to reflect the correct position within the marker, as I did not have much time to invest in the demos...
