### ISSUE TITLE
charts 2.3 unsupported architectures i386

### ISSUE THREAD

**Issue by waspnator** [danielgindi/Charts#1591]
the upload my app to apple store i received this message:

> ERROR ITMS-90087 The executable for #####.app/Frameworks/Charts.framework contains unsupported architectures '[i386]'."

**Comment by petester42** [comment]
We need more info. Installation method would be a good start.

**Comment by waspnator** [comment]
hello, thanks for replying, I'm new to xcode, the app running in the simulator and the iPhone, but on the installation, how can I do to provide more information to you?
I'm generating the xcode menu / product / archive

**Comment by waspnator** [comment]
Someone has published this framework in your project in the apple store? Can someone help me?

**Comment by petester42** [comment]
How are you installing charts?

**Comment by waspnator** [comment]
i used the pod install

`platform :ios, '8.0'
use_frameworks!
 
target ‘sindmetal’ do
    pod 'Charts’, '~> 2.3'
end`

After that used the xcworkspace file to make changes to the project!

**Comment by petester42** [comment]
Well since you are using cocoapods this is probably not an issue on our end. Cocoapods generates a framework based on our code so it uses its own settings. Either this is a cocoapods issue or a problem with your project settings. Try using the prerelease version of cocoapods and see if that fixes the problem. 

Can't be more help sorry.
