### ISSUE TITLE
HorizontalBarChartView some X values lost

### ISSUE THREAD

**Issue by hackjie** [danielgindi/Charts#1634]
- (id)initForChart:(BarLineChartViewBase *)chart
{
    self = [super init];
    if (self)
    {
        self->_chart = chart;
        
        month = @[
                   @"一月", @"二月", @"三月", @"四月", @"五月", @"六月", @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"
                   ];
    }
    return self;
}

- (NSString *)stringForValue:(double)value
                        axis:(ChartAxisBase *)axis
{
    DDLogInfo(@"haha%f", value);
    return month[MIN(MAX((NSInteger)value, 0), month.count - 1)];
}

but it shows some of months

**Comment by hackjie** [comment]
@danielgindi 
![img_1708](https://cloud.githubusercontent.com/assets/9956115/19232295/8390de84-8f11-11e6-8765-fae5dbad05d3.PNG)

you  can see the second pic, X lost some value, hope for your help!

**Comment by danielgindi** [comment]
I can't read this... @liuxuan30 can you understand what's going on there? To me it looks just like some pretty pictures, and it doesn't read like "months" to me :-D

**Comment by danielgindi** [comment]
In Israel we have a saying about something that "it is Chinese to me", like it's something that you don't stand a chance to understand. For you I guess Hebrew would fit better in the saying, or maybe ancient Egyptian...

**Comment by kientux** [comment]
I think what he meant is xAxis labels aren't always showing all of them.. I have this problem too, but with version 3.0 only. What I expects is all the xAxis labels should be shown, even when the labels count is large (because in Horizontal Bar Chart, there're so much space available to display xAxis labels).

**Comment by hackjie** [comment]
@danielgindi in fact i mean that some of XAxis didn't show up when  i use HorizontalBarChartView. it is so strange, @kientux you are right, i use version 3.0 too, guess this is a new bug, haha

**Comment by danielgindi** [comment]
Please post a sample so we can test it, the screenshots aren't speaking to me ;-)

**Comment by liuxuan30** [comment]
the axis label is Jan, Feb, ... Dec in Chinese, in month.

The label are Jan, Mar, May, July, Sep, Nov from bottom to top in horizontal bar chart.
He said not every x axis label is appearing, but to me, all the labels are present, no one is missing (except Feb, Apr, Jun... Dec). 

I don't think the chart does not show up Feb, Apr.. is a bug, it looks like it just not having those entries, because the x axis label and bars are center aligned perfectly to me. 

Need clarification @hackjie

**Comment by liuxuan30** [comment]
I think it's duplicated to https://github.com/danielgindi/Charts/issues/1646 though it's newer than this.
