### ISSUE TITLE
X labels Issues

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#1639]
Hey guys @liuxuan30 @danielgindi  I just pull the last commit but it seems that the problems with the labels still there, now even in the demo, the first label is missing, please check the image below.

![screen shot 2016-10-10 at 12 42 39 pm](https://cloud.githubusercontent.com/assets/5713880/19245695/16b84032-8ee8-11e6-93ae-428f8a6695ad.png)

Also, I'm using the configuration of the @PhilJay example to group the bars
```swift
            // (0.02 + (0.90 / total bars) ) * 2 + 0.06 = 1.00 -> interval per "group"
            let groupSpace    = 0.06
            let barSpace      = 0.02
            let totalBarWidth = 0.90
            
            newValue?.barWidth = totalBarWidth / Double((newValue?.dataSets.count)!)
            chart.groupBars(fromX:0.0, groupSpace: groupSpace, barSpace: barSpace)
```

And the result is the following:

![screen shot 2016-10-10 at 12 52 32 pm](https://cloud.githubusercontent.com/assets/5713880/19245822/d5c9835a-8ee8-11e6-8809-2d8b4c457e23.png)

As you can see the last bar stills have the same problem than before :/ 

Thanks in advance.

**Comment by liuxuan30** [comment]
Oh no, we had last label missing already and now the first label..

**Comment by liuxuan30** [comment]
@chuynadamas I checked ChartsDemo, it looks like a formatter issue for now in `DayAxisValueFormatter`. It format 0.0 as "" because 
`return dayOfMonth == 0 ? @"" : [NSString stringWithFormat:@"%d%@ %@", dayOfMonth, appendix, monthName];`

I will see if there is a neat change to fix it;

however seems you opened two issues in this thread; the other issue is not investigated yet.
