### ISSUE TITLE
'spaceBetweenLabels' not found on object XAxis

### ISSUE THREAD

**Issue by WYZKirk** [danielgindi/Charts#1643]
Hello,
I cannot found spaceBetweenLabels on object XAxis.
Was this property updated with a new name?

**Comment by LouisDhauwe** [comment]
It seems this property was removed in commit 3dbd57b5a3f78e242409d60fe0b157d995b61e81 by @danielgindi. I'm not sure what the replacement is.

**Comment by AbhishekGCopper** [comment]
Similarly **setLabelsToSkip** is missing. What are the respective replacements, if any?

**Comment by danielgindi** [comment]
There is no such thing anymore, as there are not x-indexes anymore.

We cannot skip *x* labels, because there's no whole number to compare against.
If we had an array of x-indexes [0,1,2,3,4,5], we could say that we want to skip 1, and show [0,2,4].
But now that we have x-values, say that we have [0, 0.23, 0.73, 2, 2.9, 3.2, 3.5, 3.7, 4.2, 5.1]... What exactly would we skip?

**Comment by danielgindi** [comment]
There is no more `spaceBetweenLabels`, as there's no constant distance between values. The values are not on whole indexes anymore (0,1,2,3,4,5) but on decimal values [0, 0.7, 1.2, 1.73, 2...], so there's no point in `spaceBetweenLabels` anymore.

**Comment by brenoBohm** [comment]
@danielgindi And when I use a custom value in my xAxix?
