### ISSUE TITLE
Weird highlight rect in Stacked Bar Chart Negative

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1726]
Just seeing a weird highlight for bars in Stacked Bar Chart Negative
![sbn](https://cloud.githubusercontent.com/assets/4375169/19752203/1e80a4fa-9c2e-11e6-9ac7-68736348bbbf.png)

**Comment by SumoSimo** [comment]
@liuxuan30 Hi. I can take this one if you don't mind.

**Comment by SumoSimo** [comment]
I have a fix, but I need one clarification before I'm sure it's the right approach.

What is the expected behavior when the user taps on the negative side of a bar?

Should the negative side be highlighted instead, or is the positive side always highlighted regardless of which side of the bar the user taps?

**Comment by SumoSimo** [comment]
Created pull request: https://github.com/danielgindi/Charts/pull/1744

**Comment by liuxuan30** [comment]
it should highlight the entire bar segment, not just most of it. The other segment should not be highlighted :)

**Comment by liuxuan30** [comment]
I will take a look at your PR later, thanks!

**Comment by liuxuan30** [comment]
Found new issue, stated in the PR. I am raising it to 3 stars :(
