### ISSUE TITLE
Why drawValues is outside of clipping contentRect

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1727]
@danielgindi I notice in ChartsDemo, 
`renderer!.drawValues(context: context)` is after `context.restoreGState()` so the value labels are not clipped, and when zooming and scrolling, the value text will be drawn out of contentRect, which seems strange.

Is there any purpose for this?

I am working on fixing the boundary check for `drawValues`, but I realize we could abandon all the checks but let clipping contentRect do the job.

**Comment by danielgindi** [comment]
Yes!
Look at the *Line Chart 2* demo. The values there should obviously bleed out of the content rect.

There's bounds check for drawling values, to not draw values for points which are not visible on the screen. So instead of being clipped at a certain point, you'll see that scrolling the chart will cause the values to hide abruptly.

We should probably add a flag for clipping the values too.
