### ISSUE TITLE
pod update failed - ARC Semantic Issue

### ISSUE THREAD

**Issue by Wh1rlw1nd** [danielgindi/Charts#1888]
I have a project written in Obj-C and it uses Charts pod. It worked well on Xcode 7.3.1 but after the upgrade to Xcode 8.1, an update of a pod has failed with these errors:

![ch](https://cloud.githubusercontent.com/assets/10575475/20661809/ed04386a-b550-11e6-98af-de62ee7f472c.png)

What I have tried is to run `pod update Charts` command, as it is described  [here]:(https://cocoapods.org/pods/Charts but then I got these errors. Also I have tried to re-install Charts pod, but I got  same errors (I used `pod deintegrate` and then `pod install
`)

Can somebody point me in the right direction about how to update Charts pod so I can use it in Xcode 8.1 project?

**Comment by petester42** [comment]
Could it be that you update to 3.0. It would make sense since a lot of interfaces for classes changed.

**Comment by Wh1rlw1nd** [comment]
@petester42 I tried to update to 3.0 yes. Should I do something else? Like update to 2.3 pod version?

**Comment by petester42** [comment]
Updating to 2.3 will fix your issues probably since the API for the library didn't change for that version. In 3.0 though there have been a lot of changes to how the data is constructed. I suggest you look at the demo project in 3.0 and update your code to match the new style. From the errors you got it seems like you're still using the old API but with version 3.0 which doesn't exist anymore.

**Comment by Wh1rlw1nd** [comment]
@petester42 Okay, thanks. Will try with 2.3 and let you know how it went.

**Comment by Wh1rlw1nd** [comment]
@petester42 Hm, actually if I run pod update Charts, it installs 3.0.1 version. How would I go to install 2.3 ?

**Comment by petester42** [comment]
Good to hear!
