### ISSUE TITLE
How do I implement a legend click event?

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1965]
hello , at all.  

### The  Preview
![screenshot](https://cloud.githubusercontent.com/assets/8415820/21253648/331f974c-c39b-11e6-957d-6a429143d79a.gif)

**Comment by MonkeyRing** [comment]
* 2.

![screenshot1](https://cloud.githubusercontent.com/assets/8415820/21253816/46f4a342-c39c-11e6-8d57-7dce56f03c67.gif)

**Comment by KodiKraig** [comment]
This is a good idea. After glancing it for a few minutes, I don't see an easy way to do it. I would go study the LegendRenderer class and others to try and figure out how the legend is being drawn. Since the legend is not like its own view, your going to have to get the points of each element in the legend and do something with them. Like create clear UIViews on top of them with gesture recognizers or something. Just trace through all the legend drawing code and see where it takes you. You might a simpler way.

**Comment by liuxuan30** [comment]
hmm. this is a tough task.. You need to consider using the animator and animatorJob classes. Using CoreGraphics to achieve these animations. The library does not support this yet.

**Comment by MonkeyRing** [comment]
@liuxuan30    the animations isn't important curently.   i just want achieve onclick the legend to hide corresponding bar.   have you some ideas?

**Comment by ezamagni** [comment]
You could simply implement your custom legend in a separate view, mimicking the look and feel of Chart's one.

**Comment by MonkeyRing** [comment]
@ezamagni   ha , I do think so, but the data source processing more difficult.  thank you for your answer.  :)

**Comment by liuxuan30** [comment]
@MonkeyRing Oh you are not asking animations.. Then it's much easier lol.
I used to write a UIScrollView for the legends, and you can do whatever you like.. Currently, the legend class is based on CoreGraphics, so you have to write a lot of things to make highlight and detect the touch event, which I don't recommend..
Just use a new view and read the data you need to create the legend and some delegates to synergy with chart library seems doable and flexible, but it is a descent amount of work.
