### ISSUE TITLE
How to add dates to line chart?

### ISSUE THREAD

**Issue by f15handch1p5** [danielgindi/Charts#2136]
Hi , i'm fairly new to this api and ios in general; i have looked at the demo's but i still can't figure out how to add date labels to the x axis on my line chart. Just wondering if anyone could point me in the right direction to achieve this. Would be much appreciated, thanks.

**Comment by elchris78** [comment]
haven't you had any response to this? I'm through the same exact problem and haven't found any response to this.

**Comment by liuxuan30** [comment]
Just take a look at ChartsDemo, there are already `DateValueFormatter` example.
Basically, it convert a x value to an string via `- (NSString *)stringForValue:(double)value axis:(ChartAxisBase *)axis`

**Comment by Aaimek** [comment]
I'm having trouble with this feature and solving it may help people looking for how to add dates to line chart.

My `LineChartDataSet` only has `ChartDataEntry`e's where x values are the `timeIntervalSince1970` for round hour dates (12:00, 13:00 etc...). But in my `DateValueFormatter.stringForValue`, that recreates the dates like that:
`let date = Date(timeIntervalSince1970: value)` 
Returns the same dates as the ones in `LineChartDataSet`, but also some weird dates where the hour is not round (Ex: 16:48).

I don't understand where those dates come from since I didn't input non-rounded hour dates.

I'm doing what I understood from the 'time line chart' demo but I may haven't understood it correctly.

Help would be much appreciated, thank you.
