### ISSUE TITLE
Branch Chart3.0-Swift2.3 not found.

### ISSUE THREAD

**Issue by bharat-madept** [danielgindi/Charts#2166]
Hi Daniel,

I was using `Chart3.0-Swift2.3` branch in my code and it was working fine until i update my pod file. Now if i want to update pods its give me error that branch not found.
Here is what i 'm using in my pod file-
`pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Chart3.0-Swift2.3'`

Please help.

**Comment by petester42** [comment]
That branch was deleted because we never supported swift 2.3 and charts 3.0. This was well stated that we weren't going to support that. In order to keep people from using that branch and filing issues we deleted it when charts 3.0 became final. 

I suggest you update to swift 3.0 as soon as possible. Apple is dropping support for swift 2.3 in the next Xcode version.

**Comment by bharat-madept** [comment]
Thanks for your reply. Can you please suggest commit id till `Chart3.0-Swift2.3` was supported. that branch was working fine for me. And Our app is live on the app store and we want to fix a minor bug.

Updating to Swift 3 will be a time-consuming process and as we need to check for other libraries as well our source code.

**Comment by petester42** [comment]
I sorry you're having troubles but we never supported swift 2.3 and charts 3 because of the effort it would take to do so. There are other forks around that are swift 2.3 and charts 3 but we don't support them (just search the issues and you'll find them) 

This is a good lesson to learn though. Don't use dependencies that not production ready.
