### ISSUE TITLE
Xcode 9 compatibility

### ISSUE THREAD

**Issue by Keetoo** [danielgindi/Charts#2883]
When we will get a swift 4.0 version of this lib.

Thanks 
Maddy

**Comment by jamiedaniel** [comment]
Agreed. Where is the fix for the new Swift 4.0 version?

**Comment by liuxuan30** [comment]
WTH? Don't you check any README or search first and finding out it's already done by a long time?

**Comment by jamiedaniel** [comment]
Really?
Explain the errors that complain over compiler issues even with your latest build using cocoapods, marked for iOS 11 and Swift 4 and embed Swift libraries as $(inherited)...

And as a side note, being an ass when people appreciate your hard work and request something that could have been answered without that attitude, is beneath you.

Duly noted.

**Comment by liuxuan30** [comment]
alright, my apology. I have been answering and closing such issues for many times. What's the issue then? ChartsDemo as well as ChartsRealm just works as usual, why you say it's not?

**Comment by jamiedaniel** [comment]
Thank you,

It's weird. Usually when you use cocoapods, the pod downloads and it works out of the box. This time I imported the pod 'Charts' and then when it was time to open the workspace, there were about 60 errors in Charts. I then decided to check Xcode settings and ensure that the version of iOS was set to 11, it was. I checked the pod to ensure it was set to Swift version 4.0 - it wasn't. I changed the setting. I then set the embed Swift libs to $(inherited), and I am not sure why this made a difference, I never had to do it before. Then I tried to build.
There was an error that was generated that said... Charts framework: bundle format unrecognized, invalid, or unsuitable. I cleaned the project and then closed Xcode. I then opened the project workspace and tried to build again. No luck. I then used cocoapods to pod update. It set everything back to the original values. Drat!

I then removed it from the Podfile and pulled the repo down from the repo. I then dragged it into the project and tried to build. Then I had the issue that was due to the incorrect version of Swift. I set the version of swift to 4.0 ( I do not understand why it is defaulting to 3.2 but whatever)

I was able to build and get a sample project to work.

I tried this on two different projects - a new project created in Xcode 9/Swift 4.0 and an older project that was created in Xcode 8.3/Swift 3.3

The error persisted in all attempted while trying to use cocoapods.

I can only assume it was something wrong with my version of Xcode - so I removed and reinstalled it.
Same behavior.
I can only assume it was something wrong with the project - so I recreated it.
Same behavior.

I have not tried it on a new machine.
I have updated all gems on my laptop and included cocoapods in the update.

I can't quite understand the issue. What I read online was associated with the library not conforming to Swift 4 so I tagged the open issue. Then after I read some more I know that wasn't the case, but wasn't near my computer to remove my comment to the issue.

Have you ever seen the error - framework: bundle format unrecognized, invalid, or unsuitable - with Charts?

I will test on another laptop in the morning and let you know what I find. I am sure I'm not the only one having similar issues. For all I know it could be updated gems and cocoapods being moody.

Anyway, thanks for hitting me back, we really like your framework and use it in our prototypes. We are actually looking at making some pull requests with some changes we have made.

Have a great evening and I'll check back in tomorrow with progress on the bug ( on my side I'm sure )

J


On Oct 16, 2017, at 10:09 PM, Xuan <notifications@github.com> wrote:

alright, my apology. I have been answering and closing such issues for many times. What's the issue then? ChartsDemo as well as ChartsRealm just works as usual, why you say it's not?

**Comment by liuxuan30** [comment]
People usually asked Pod and get an answer, but never reply back, so we assume it works. People usually do several things:
1. point pod spec to master branch; or a specific release
2. clean and rebuild. 
3. update your pod version

sometimes No.3 will pull the trigger, so you should try it out.

Personally I prefer carthage over pod, so my pod knowledge is limited as well. but in terms of framework, I don't think pod will do anything more. They just download the framework and modify some build settings to get it work.
