### ISSUE TITLE
How to represent a null value，It's like the picture? not 0

### ISSUE THREAD

**Issue by guoyutao** [danielgindi/Charts#3052]
![image](https://user-images.githubusercontent.com/11513385/33210290-8cb1dd48-d154-11e7-8e97-49033de74870.png)

**Comment by HudsonGraeme** [comment]
If you're working in Swift, and you encounter a nil value, then add error trapping to still add a nil value; something like the following would maybe work
`if(temperature == nil) {
temperature =0
} else {
//Add to to chart
}
`

I'm surprised the application didn't crash when the chart had to deal with the null (nil value). Since nil is not a valid chart value, the chart can't do anything with it, hence an empty space. It is your job to deal with nil values.

**Comment by guoyutao** [comment]
You don't understand what I mean.I mean, how to achieve this effect,like the picture?

**Comment by HudsonGraeme** [comment]
Oh, I gotcha. Have you tried using `nil`?

**Comment by thierryH91200** [comment]
use 2 dataset it's simple
first dataset       => x1 = 0 .. n
second dataset => x2 = n+1 .. m

**Comment by guoyutao** [comment]
@HudsonGraeme    I've tried this way, But the Bouble type doesn't match.I've done by The way that @thierryH91200  provided

**Comment by HudsonGraeme** [comment]
@guoyutao Glad you have it working, sorry I wasn't of much help.
@thierryH91200 Cheers!

**Comment by littledogboy** [comment]
@thierryH91200 That's a good idea!

**Comment by xiaowasly** [comment]
@guoyutao How did you achieve that, I also encountered a similar problem, can answer in detail
