### ISSUE TITLE
Is it possible to draw a chart like this?

### ISSUE THREAD

**Issue by mo3bius** [danielgindi/Charts#3097]
Hi I need an advice. I have to do a chart in my app and I was looking the library examples but I didn't find one like my attachment. Is it possible to do that with this library?
![schermata 2017-12-13 alle 17 49 34 2](https://user-images.githubusercontent.com/11818717/33950987-130f4622-e02e-11e7-85ed-f40485c71ee5.png)

**Comment by liuxuan30** [comment]
Because this is not a very common chart? 
If goes for line chart,

Just find a way to generate those small filling rects so you are good to go.
If goes for bar chart:
override bar chart renderer, by changing how it generate the barRect. It's just a matter that you give more data for each bar, and you manually connect those dots to be the new bar. 

About the color, and other stuff, similar, but requires you override lots of things and add some new methods to draw exactly the same.
