### ISSUE TITLE
X Axis disapeared

### ISSUE THREAD

**Issue by Susanou** [danielgindi/Charts#3249]
Hello,
I've been trying to fix this issue, in charts 3.4.0 the x-axis was displayed on top with dates but now since I update to 3.5.0 is disappeared.

![img_fca79f91b20a-1](https://user-images.githubusercontent.com/24324166/35945528-851cdcbc-0c2e-11e8-9e94-52be653ca84b.jpeg)

**Comment by mikeCalvir** [comment]
I have this same issue. I see elsewhere that people can get it to work in 3.0.4, but for me the X-Axis never shows, I have 3.0.4 installed. Everything else works fine. I have two charts, a Line chart and a Combi with line and scatter.

If you find another way that solves this I would be interested :)

**Comment by simbo64** [comment]
So I too was having this issue with 3.0.5 but not with 3.0.4
What was confusing was I downloaded the demo project and that was working fine, In the end from running a diff and also looking at the commits since 3.0.5 I found the offending line for me to be in the IndexAxisValueFormatter.swift file. Line 56 should be == and not != . 
Try changing that and see if it fixes the issue for you.
No idea why this got through the 3.0.5 release and no idea why it causes the issue but changing it has fixed it for me!

**Comment by liuxuan30** [comment]
@simbo64 Thanks for helping. Is there a PR for this already? Why I remember I just saw a similar fix of != and == recently.
This will be address in 3.1 release soon. Just let me know if there is a PR or what should I look into

**Comment by liuxuan30** [comment]
@simbo64 I looked at master branch, seems IndexAxisValueFormatter.swift line 56 is arealdy ==:
would you please help verify?https://github.com/danielgindi/Charts/blob/0011c353bd58f0fa60a7b5929804ee99b72ef03f/Source/Charts/Formatters/IndexAxisValueFormatter.swift

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/pull/3174 it is. Seems already fixed. Please wait for 3.1 or just grab master branch. Sorry for a mistake.
