### ISSUE TITLE
Swift Documentation

### ISSUE THREAD

**Issue by cagricolak** [danielgindi/Charts#3358]
the company that I work with has only iOS department and there is no working for android and i do not know the android programming language.

why not documentation for swift?

thanks
Çağrı.

**Comment by liuxuan30** [comment]
because we lack of people for that. You can use ChartsDemo and the source code to get started. Code explains everything, right?

I used to investigated using Jazzy to generate a API doc and publish to Dash, but at that time, Jazzy is not working very well.

Maybe we will  revisit and make some improvements
