### ISSUE TITLE
Open up Access Modifiers?

### ISSUE THREAD

**Issue by seenoevo** [danielgindi/Charts#3391]
Previously I've been manually dragging the source files into my project and accessing whatever I need with no issues.

I have started migrating to using CocoaPods for easier future updates, and have ran into some issues.

I have subclassed `PieChartView` to modify the Pie Chart and am facing some issues:

![untitled](https://user-images.githubusercontent.com/8109158/38601397-42b0ed18-3d1c-11e8-9046-c17b369175dc.png)
![untitled2](https://user-images.githubusercontent.com/8109158/38601930-1131b0e0-3d1e-11e8-928e-7623f6e149a5.png)

@liuxuan30 

1.  Can the modifier in `PieChartView` be changed from `internal` to `open` so we can override it?...i.e. `internal override func calcMinMax()` to `open override func calcMinMax()`

This will allow me to override it in my subclass: `public override func calcMinMax()`

2. Can the modifier in `ChartViewBase` be changed from `internal` to `open` so we can gain access to it in our subclass?...i.e. `internal var _data: ChartData?` to `open var data: ChartData?`

3. Can the modifier in `ChartViewBase` be changed from `internal` to `open` so we can gain access to it in our subclass?...i.e. `@objc internal var _indicesToHighlight = [Highlight]()
` to `@objc open var indicesToHighlight = [Highlight]()`

I've temporarily changed it for the time being, but I hope you can update the library to include this for us?

Thanks!

**Comment by liuxuan30** [comment]
well, we are working on Chart 4.0 and swift refactoring. You can check 4.0 branch if it solves the issues. If 4.0 branch does not meet, you can file a PR against 4.0 branch, we will decide if it's ok to make it open.

However, I will point out some methods are meant to be internal or private by design. 

If you need to modify, then pick up the source code. But making everything public is not a good design I think. Otherwise there is no need to have access control system.
