### ISSUE TITLE
xAxis labelText too long, it can not draw complete.

### ISSUE THREAD

**Issue by fengqiangboy** [danielgindi/Charts#3430]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag [`ios-charts`.](https://stackoverflow.com/questions/tagged/ios-charts)
>
> Please remove this line and everything above it before submitting.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Draw charts

## What did you expect to happen?

xAxis labelText can draw complete

## What happened instead?

The first and last xAxis label can not draw complete

## Charts Environment

**Charts version/Branch/Commit Number:3.1.1
**Xcode version:9.3
**Swift version:4.1
**Platform(s) running Charts:iOS
**macOS version running Xcode:10.13.4

![image](https://user-images.githubusercontent.com/13598763/39390762-f570a990-4acb-11e8-9b9d-4763d83640ff.png)

**Comment by liuxuan30** [comment]
ask on stack overflow.
For courtesy, 
A) using `avoidFirstLastClippingEnabled`
B) enable x axis label wrapping

**Comment by Karpot** [comment]
I have the same issue. A) doesnt look good, because I only need it for the last one. When I use the "Debug View Hierarchy" I see that the complete chart is some pixels to the right placed.

I think the real solution is to calculate the first and last label in respect of the view boundaries. It may change the hole chart.

I dont want to comennt such a closing with a "works as expected" for now. :-/
