### ISSUE TITLE
The maximum value of the histogram is not shown.

### ISSUE THREAD

**Issue by ziyanliu** [danielgindi/Charts#3447]
The maximum value of the histogram is not shown.
<img width="156" alt="2018-05-08 2 08 36" src="https://user-images.githubusercontent.com/17906822/39740745-8db63f30-52c9-11e8-9fc7-d5fbb814e335.png">

**Comment by liuxuan30** [comment]
for generic questions, please ask on stack overflow. We only accept bugs and topics to improve the library. 

If you think this is a bug, you need to provide details as well as samples so we could confirm, rather than saying a simple 'something not work'. For courtesy this time, it looks like you set axisMaximum of your y axis.
