### ISSUE TITLE
How can I plot all Axis Value?

### ISSUE THREAD

**Issue by haroldogtf** [danielgindi/Charts#3540]
## What did you do?

I am using xAxis with IAxisValueFormatter

I want to show these labels:
`let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
`
## What did you expect to happen?

Show all values of my formatter: `["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]`

## What happened instead?

Not show all, show only: ` ["Jan", "Mar", "May", "Jul", "Sep", "Nov"]`

![untitled](https://user-images.githubusercontent.com/1682169/42068001-cb244d0c-7b1f-11e8-938a-3ce3c4c5d204.png)

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1.1
**Xcode version:** 9.4.1
**Swift version:** 4.
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.13.5

**Comment by chenhaibo** [comment]
the same question !

**Comment by CodingEleven** [comment]
So it is the question that how to set the space between the xAxis label !
Maybe you can use " [_lineChart setVisibleXRangeMaximum:6] //最大显示6个数据; " to show 6 data in the chart and others for scrolling .

**Comment by haroldogtf** [comment]
I tried to use granularity, but even then the labels did not appear as I expected.

I expected all those visible ` ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]`

**Comment by bsachetta** [comment]
I've been stumped by the same issue for the last couple of days. I've read a bunch of different solutions but still haven't come up with anything.  I think this thread sums it up well: https://github.com/danielgindi/Charts/issues/1340

The thing that isn't making sense to me is: if you have a month for which there is no data (let's say March, or 2 in Int representation), it appears as though your custom value formatter will never call stringForValue(_ value: Double, axis: AxisBase?) with a value of 2.

I'm pretty sure that's why you're seeing the wrong month labels and why I can't get my chart to work either.

**Comment by bsachetta** [comment]
See if this thread is helpful at all: https://github.com/danielgindi/Charts/issues/3557. We were able to figure out how to get day of week labels to show even without backing data. The code can easily be modified to support months (I actually had to do that in my project as well - it's pretty straightforward).

Here's the answer I refer to in the issue thread I linked to above: https://stackoverflow.com/questions/51333345/ios-charts-library-x-axis-labels-without-backing-data-not-showing
