### ISSUE TITLE
Performance hit

### ISSUE THREAD

**Issue by sejr** [danielgindi/Charts#3585]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

I am building an application that has a collection view, where each collection view cell contains some kind of chart. Upon implementing this with test data, I have noticed a significant performance decrease and am curious if others are experiencing this issue.

## Charts Environment

**Charts version/Branch/Commit Number:** latest (Cocoa Pods)
**Xcode version:** 10.0 Beta 4
**Swift version:**
**Platform(s) running Charts:** iOS 12 Beta
**macOS version running Xcode:** 10.13.6

**Comment by sejr** [comment]
It's important to note this issue only occurs when there is a search controller or large title present.

**Comment by petester42** [comment]
There are so many factors for performance issues that it would be hard to narrow down an issue with this little details. That being said, the fact that you mention specifically search controller and large title being causing the issue indicates to be that it probably has nothing to do with our library. Our library basically takes a bunch of points and draws them with core graphics, I don't see how adding a large title would affect core graphics drawing unless there is a bug on apple's side.

In addition, since you mention collection views specifically, I don't think its a good idea to have live charts in cells if you're concerned with performance. I could see the performance being bad in your app since your drawing a lot of stuff in each cell.

**Comment by jjatie** [comment]
To add on to @petester42 comment about using Charts in reusable views, if you absolutely must, I would render the graph into a bitmap in your prefetching methods and display that.
