### ISSUE TITLE
Adding text data points to axis

### ISSUE THREAD

**Issue by Sviests** [danielgindi/Charts#3592]
I am very new to swift so I might be doing something wrong, but I cannot find a way to add String data points to any axis (e.g. line chart with numerical values on y-axis and months (Jan, Feb etc...) on the x-axis). I see in tutorials that this is added to the ChartData but for me it only takes the ChartDataSet...

Thank you in advance!

**Comment by NSAmit** [comment]
@Sviests 
You have to make sure you are doing following to show labels on xAxis - 
chartView.xAxis.drawLabelsEnabled = true
chartView.xAxis.valueFormatter = self // In case you want to format the values on your own

Also, recommend you to look at the demo code so that you will get clear idea. I also used it first time in my app and I am loving this library. But the key thing which helped me a lot is to play around with the demo app. Try changing some properties and updating some values in demo app to get clear understanding for this beautiful lib.

**Comment by abhi137** [comment]
I did something like this -

```
self.lineChartView.xAxis.valueFormatter = DefaultAxisValueFormatter { (value, axis) in
            if (value == 0) {
                return "Now"
            } else {
                return "8/26"
            }
        }
```

**Comment by liuxuan30** [comment]
for beginners, stack overflow is the better place to ask.
