### ISSUE TITLE
Compilation errors with Swift 4.1

### ISSUE THREAD

**Issue by Mohamed3amer** [danielgindi/Charts#3596]
## What did you do?

ℹ Trying to use Charts on xCode 9.4.1 and Swift 4.1

## What did you expect to happen?

ℹ Building without errors 

## What happened instead?

ℹ Received a lot of compilation errors, check screenshot:
[screenshot](https://ibb.co/npMM3z)

- Cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available

## Charts Environment

**Charts version/Branch/Commit Number:** pod 'Charts'
**Xcode version:** 9.4.1
**Swift version:** 4.1
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** High Sierra 10.13.5

**Comment by liuxuan30** [comment]
can you try to clean and rebuild? My side is fine.

**Comment by Mohamed3amer** [comment]
Why I should ask on stackoverflow not here ?
And why did you close the issue before I confirm that is working with me ? BTW still not working!

**Comment by liuxuan30** [comment]
closing does not mean we won't update. It's just a way to control the real issues. Pod issue usually doesn't count as it's fine on my side.

That's why we ask you to stack overflow: 1 more people to help; 2 it sounds like a pod setup issue rather than Charts.

And from what I know that, you are the only very few people complaining pods not working. So I'd assume it's your env problem. And we have no idea what's the reason and how to fix it.

**Comment by yaalisri** [comment]
@Mohamed3amer Even i am facing the same issue. I just opened my project using Xcode 9.4.1 and used pod update to update all pods. This installed the recent version of Charts 3.1.1 to my project. After this installation i am getting lot of compilation errors. If i don't update the version, the older version is 3.0.2, i am getting lot of compiler warnings including deprecations.
