### ISSUE TITLE
barchartview draw value in bottom of chart

### ISSUE THREAD

**Issue by fukemy** [danielgindi/Charts#3827]
Hi. I saw the value of data is above barchart, how can i put it below barchart?

**Comment by LiubovFedorchuk** [comment]
Hi, try to do this:
` chartView.drawValueAboveBarEnabled = false 
 // if set to true, all values are drawn above their bars, instead of below their top`

Or are you speaking about columns of BarChart? If yes, then take a look at this demo class [PositiveNegativeBarChartViewController](https://github.com/danielgindi/Charts/blob/master/ChartsDemo-iOS/Swift/Demos/PositiveNegativeBarChartViewController.swift). 

If you're speaking about values in labels, then try to do this part:
```
 let xAxis = chartView.xAxis
 xAxis.labelPosition = .bottom
```
