### ISSUE TITLE
Horizontal scrolling in long vertical tableView causes the outer table to jump

### ISSUE THREAD

**Issue by gklka** [danielgindi/Charts#3866]
[*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I have a zoomable LineChartView in my UITableView.

## What did you expect to happen?

I expected the outer table view not to scroll (jump) vertically when I started scrolling the chart.

## What happened instead?

I the outer table view jumped ~44 pt vertically when I started scrolling the chart. This was caused by Platform.swift:155 isScrollEnabled = true.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.2
**Xcode version:** 10.1
**Swift version:** Objective-C and 
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.3

## Demo Project

![simulator screen shot - iphone 8 - 2019-02-25 at 15 52 17](https://user-images.githubusercontent.com/866694/53345661-b416cb80-3915-11e9-8474-931a85b6f582.png)

https://imgur.com/a/mgFw2Nl

**Comment by liuxuan30** [comment]
take a look at `panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)`

```swift
                    if _outerScrollView !== nil
                    {
                        // Prevent the parent scroll view from scrolling
                        _outerScrollView?.nsuiIsScrollEnabled = false
                    }
```
it should be disabled already. But I don't know what's going on on your side. Please debug a little

**Comment by CodeStrumpet** [comment]
Hi @gklka I was experiencing the same thing when panning my LineChartView that was within a tableview. Not sure if this is relevant to your situation but in my case I found that it was related to the tableview automatically adjusting the content insets. When I set the contentInsetAdjustmentBehavior property of the tableview to "never", the problem stopped happening, however my tableview content was now occluded by my navigation bar.

`self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;`

What I discovered is that when I allocated my tableview I had set its frame to my view bounds which placed it under my navigation bar. Because the content insets were being updated automatically, none of my tableview cells were occluded by the navigation bar however I was experiencing the vertical jump that you mentioned when panning my chart. 

Ultimately I found the best solution for me was to re-enable the automatic content inset adjustment behavior, but correctly set the origin Y of my tableview frame to be below my navigation bar.
