### ISSUE TITLE
Crash at BarChartDataSet as! IBarChartDataSet

### ISSUE THREAD

**Issue by anekk** [danielgindi/Charts#3917]
## What did you do?

Create BarChartData with BarChartDataSet with BarChartDataEntry.

## What did you expect to happen?

See bar chart.

## What happened instead?

App crashed.
![Zrzut ekranu 2019-03-27 o 11 21 53](https://user-images.githubusercontent.com/2115211/55068622-92c70d80-5082-11e9-9be7-dc2ea526bd24.png)

"Could not cast value of type 'Charts.ChartDataSet' (0x108ede670) to 'Charts.IBarChartDataSet' (0x108e8f868)."

BarChartDataSet is  IBarChartDataSet.

Before update to xCode 10.2 it works.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.2
**Xcode version:** 10.2
**Swift version:** 4
**Platform(s) running Charts:** iOS 12.2
**macOS version running Xcode:** 10.14.4

## Demo Project

https://github.com/anekk/ChartsIssue.git

**Comment by joshxplor** [comment]
Having the same issue wherein after setting the `BarChartDataSet` I invoke `highlightColor = .someColor` and it just crashes

**Comment by liuxuan30** [comment]
>"Could not cast value of type '**Charts.ChartDataSet**' (0x108ede670) to 'Charts.IBarChartDataSet' (0x108e8f868)."

apparently you are not passing in a `BarChartDataSet`

**Comment by kapisz** [comment]
> > "Could not cast value of type '**Charts.ChartDataSet**' (0x108ede670) to 'Charts.IBarChartDataSet' (0x108e8f868)."
> 
> apparently you are not passing in a `BarChartDataSet`

After reviewing the demo project to verify that it works and comparing it to my code which doesn't, I think I have an idea as to what's going on. I've instantiated BarChartDataSet as
`BarChartDataSet(myArrayOfBarChartDataEntries)`
instead of the equivalent in the demo project
`BarChartDataSet(values: myArrayOfBarChartDataEntries, label: nil)`
the former example seemingly utilizing the initializer in ChartDataSet
`
@objc public convenience init(values: [ChartDataEntry]?)
`
and now for whatever reason Xcode 10.2+ seems to be treating the type of value returned as ChartDataSet instead of BarChartDataSet (even though the debugger claims the type to be BarChartDataSet).

**Comment by liuxuan30** [comment]
I tried your demo, and it's true indeed.

@jjatie would you take a look? It smells a bug to Apple, not us.

I checked when break at 
```
        let set = BarChartDataSet(values)
        let data = BarChartData(dataSet: set)
```
set is still BarChartDatSet:
> (lldb) fr v set
(Charts.BarChartDataSet) set = 0x000000028109c000 {

but in
```
let set = barData.dataSets[i] as! IBarChartDataSet
```
it's 
>(lldb) p barData.dataSets[i]
(_TtC6Charts12ChartDataSet) $R6 = 0x000000028109c000

note the pointer address is still the same, but failed to cast to `BarChartDataSet` nor `IBarChartDataSet`

**Comment by jjatie** [comment]
Looks like there are some issues when keeping objc support around. We need to override the initializer in the subclasses, then it works fine.

**Comment by liuxuan30** [comment]
@jjatie but it seems weird to just override only for override, right? I suppose we should file radar for apple?

**Comment by liuxuan30** [comment]
@kapisz I reset my branch to 3.2.2 release, and your demo still the same issue. I didn't have an older Xcode on my side, so I don't know if this is introduced with Xcode 10.2

But like what @jjatie said, we can override all super class's designated initializers to make it inherit all superclass's convenient initialziers. seems the only solution for now.

**Comment by kapisz** [comment]
I had to put my thinking cap on and really dig for this one @liuxuan30 , but I do think Xcode broke it rather than fixed it. First and foremost I was wrong, that is, BarChartDataSet(myArrayOfBarChartDataEntries) was never calling `init(values: [ChartDataEntry]?)` in ChartDataSet so this isn't an issue where initializers are available when they shouldn't be given the inheritance rules stated in the link you provided. What it's actually calling is `init<S>(_ elements: S) where S : Sequence, Self.Element == S.Element` of the RangeReplaceableCollection protocol as you discovered earlier, which then calls `required init()` that ChartDataSet conforms to and BarChartDataSet inherits from (and populates the 'values' field using the implemented append method of RangeReplaceableCollection). The interesting thing is that while testing with breakpoints, prior to Xcode 10.2 the `public required init()` method in BarChartDataSet was called but since Xcode 10.2, it's the init method in ChartDataSet being called when instantiating with a Sequence as the argument. The unfortunate thing is that because it's instantiating with the conforming class rather than with the intended class when passing a Sequence as argument will cause typecasting to fail elsewhere as well (e.g. Instantiating PieChartData with a PieChartDataSet).

**Comment by liuxuan30** [comment]
@kapisz yes, that's why I said the cast failure should be a bug of Apple. 
if it's calling `init<S>(_ elements: S)`, everything should be fine because of we adopted the collection protocols.

but it could take a long time to get it really fixed, so I made the change you could call 
>public convenience init(entries: [ChartDataEntry]?)

on your side by just adding an argument label "entries". 

I don't remember if old Swift allows to automatically omit the argument label if there is only one parameter without `_` being specified. But to my knowledge, `let set = BarChartDataSet(values)` should never work in any versions, because this intializer is not inherited at all. I just wonder why this is revealed until now.

**Comment by kapisz** [comment]
Hopefully this is what you were asking for.

Running my project using Charts 3.2.2, here are the pertinent steps occurring in order.
1. Initialize my BarChartDataSet:
<img width="922" alt="Screen Shot 2019-04-26 at 12 31 33 AM" src="https://user-images.githubusercontent.com/2817132/56787977-60145000-67bb-11e9-9d07-a92be1646962.png">
2. `init` in BarChartDataSet is called:
<img width="670" alt="Screen Shot 2019-04-26 at 12 32 01 AM" src="https://user-images.githubusercontent.com/2817132/56788025-8c2fd100-67bb-11e9-81bd-af33ec290522.png">
3. 'init' in ChartDataSet is called after calling super in step 2:
<img width="411" alt="Screen Shot 2019-04-26 at 12 32 25 AM" src="https://user-images.githubusercontent.com/2817132/56788073-aa95cc80-67bb-11e9-8ebb-ae816e465a0a.png">
4. `append` is called repeatedly adding a new BarChartDataEntry for each `Element`.
<img width="457" alt="Screen Shot 2019-04-26 at 12 32 38 AM" src="https://user-images.githubusercontent.com/2817132/56788096-b8e3e880-67bb-11e9-890e-8408e0aba08c.png">

And in case if you wanted to know what `barChartDataEntries` is:
<img width="489" alt="Screen Shot 2019-04-26 at 12 41 39 AM" src="https://user-images.githubusercontent.com/2817132/56788267-36a7f400-67bc-11e9-87e9-0951dffa246a.png">



Running the same project in Xcode 10.2 (and 10.2.1), everything happens again the same way EXCEPT step 2 never occurs. Init is called on ChartDataSet (step 3) and the debugger says the set returned is of type BarChartDataSet but the project crashes exactly the way the original poster described it and how you were able to replicate it.

**Comment by liuxuan30** [comment]
I see. What I said 
>But to my knowledge, let set = BarChartDataSet(values) should never work in any previous versions before we adopt collection protocol, because this initializer is not inherited at all.

seems wrong. 3.2.2 already adopted collection protocol. before 3.2.2 we don't have this initializer at all

**Comment by jjatie** [comment]
@liuxuan30 This is a known issue [49303574](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_1_release_notes/)

**Comment by liuxuan30** [comment]
@jjatie good to know. but I think our workaround can also do the job. but I kind of oppose we use the 'static func workaround' mentioned in 49303574 now. It's not a small effort to add and later remove it.

and I'm kind of disappointed such major issue is released to outside devs... it should be fixed before :(
