### ISSUE TITLE
Height of Half Pie Chart (white space in the chart where the removed bottom half from pie chart should be)

### ISSUE THREAD

**Issue by ratala1** [danielgindi/Charts#4033]
I am using Half Pie Chart in my project. When I reduce the height component of the pieChart, the chart size also goes down. attaching screenshots for reference. How do I use HalfPieChart without the extra space below the chart?

Screenshot 1:
Height = Width
![Simulator Screen Shot - iPhone Xʀ - 2019-06-20 at 15 31 10](https://user-images.githubusercontent.com/11667120/59841594-441fcb80-9372-11e9-8dd0-aa51f1fb558f.png)

Screenshot 2:
Height = Width/2
![Simulator Screen Shot - iPhone Xʀ - 2019-06-20 at 15 28 20](https://user-images.githubusercontent.com/11667120/59841621-5437ab00-9372-11e9-8008-08c23a65db22.png)

Thanks

**Comment by kamokaizen** [comment]
did you solve it? same problem i have and can not resolved yet.

**Comment by ratala1** [comment]
@kamokaizen no

**Comment by kamokaizen** [comment]
to solve with workaround; give below item of chart a minus top padding.  i m using snapkit;
make.top.equalTo(chartView.snp.bottom).offset(-100) // 100 mean height/2

**Comment by JMSerruya** [comment]
Hi @ratala1 , did you found a fix to this issue? facing the same problem.

**Comment by liuxuan30** [comment]
I'm feeling it's kind of a defect, that it still counts as a full pie chart view and reserves the bottom half. The workaround seems correct by @kamokaizen, which is to reduce the offset. However, a true solution is not that easy - and we might need someone to look into it.

**Comment by liuxuan30** [comment]
The tricky part here is if you want the radius to be larger, you have to calculate the radius properly;

for example, I faked the radius with ChartsDemo half pie chart:
```swift
    internal override func calculateOffsets()
    {
        super.calculateOffsets()
        
        // prevent nullpointer when no data set
        if _data === nil
        {
            return
        }
        
        let radius = maxAngle > 180 ? diameter / 2.0 : (_viewPortHandler.contentRect.size.width > _viewPortHandler.contentRect.size.height ? diameter : diameter / 2)
        
        let c = self.centerOffsets
        
        let shift = (data as? PieChartData)?.dataSet?.selectionShift ?? 0.0
        
        // create the circle box that will contain the pie-chart (the bounds of the pie-chart)
        _circleBox.origin.x = maxAngle > 180 ? (c.x - radius) + shift : (c.x - radius) + shift
        _circleBox.origin.y = maxAngle > 180 ? (c.y - radius) + shift : (_viewPortHandler.contentRect.size.width > _viewPortHandler.contentRect.size.height ? (c.y - radius / 2) + shift : (c.y - radius) + shift)  
        _circleBox.size.width = radius * 2 - shift * 2.0
        _circleBox.size.height = radius * 2 - shift * 2.0

    }
```
The key idea is to fake the radius and adjust the circle box. 

when screen width < height, it should be the same as a full pie chart, since the radius should be diameter(min(width, height) / 2) anyway;

but when screen width > height, the radius is min(width, height) to use the maximum space:
![image](https://user-images.githubusercontent.com/4375169/72673957-1f2c3c00-3aac-11ea-897e-c2128738f459.png)

Currently the highlight is partial broken in this state. If you don't mind the highlight, you can use the code directly. The touch point calculation and mapping to slice is more complex than I can fix right now. I hope someone can carry on if interested.

**Comment by liuxuan30** [comment]
after the last retry today, it seems the highlight is fixed.

can you guys give a try? I didn't plan to merge this any time soon before we thoroughly tested and reviewed it. 

any suggestions and review are welcome.
