### ISSUE TITLE
3.2.2 xBounds starts from 1

### ISSUE THREAD

**Issue by Andy1984** [danielgindi/Charts#4073]
Hi developers, 
I encounter a problem and need your help.
3.2.2 Run the demo and open Scatter Chart.
Break point in Line 146 in ScatterChartRenderer, `for j in _xBounds`. 
In 3.2.2, j starts from 1, which is not correct and lead to that some labels and icons are not shown when isDrawingValuesAllowed.
In 3.3.0, j starts from 0, which is correct.
I checked the xBounds, both of them are correct.
I do not use 3.3.0 because of bug #3908.

How do I fix this issues without changing the source code?

Thank you very much.

**Comment by liuxuan30** [comment]
is this same as #3960?

**Comment by liuxuan30** [comment]
ah my bad. I was thinking you are saying the xBounds has bugs, after I tried I found out you are asking another one. You have to either:
A. pick up the source code and modify;
B. use a subclass to override it

However, I don't know why it's related to #3908, because no version support it. There is no point you don't use 3.3 because of it
