### ISSUE TITLE
Mac Catalyst compile error: no such module 'Charts'

### ISSUE THREAD

**Issue by stefat** [danielgindi/Charts#4380]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ In a new iOS project for iPhone, iPad and Mac Catalyst I import (manually: not using pod) the Charts frameworks. Everything works fine and the app compiles and runs for iPhone, iPad using Charts. Fairly good so far. Compiling for Mac OS with Mac Catalyst I get the "no such module 'Charts'" error. This is related to the Charts framework as the app, before importing Charts, was running using Catalyst flawlessly. 

## What did you expect to happen?

ℹ I've read the four (at the time) issues that glows under the 'Mac Catalyst' search in the Charts issues blog. No way to fix. Can someone give some help on this ?

## What happened instead?

ℹ see above  

## Charts Environment

**Charts version/Branch/Commit Number:**Version 3.5.0, synced to MPAndroidChart #f6a398b
Commit: bf3080f
**Xcode version:** Xcode Version 11.5 (11E608c) 
**Swift version:**5.0
**Platform(s) running Charts:**iOS and MacOS
**macOS version running Xcode:**Catalina 10.15.4 (19E287)
[CASHPLAN_demo.zip](https://github.com/danielgindi/Charts/files/4706147/CASHPLAN_demo.zip)

## Demo Project

ℹ You can download the zipped demo project here: 
https://www.dropbox.com/s/4p2g46hordr5465/CASHPLAN_demo.zip?dl=0

Thanks all !
Stefano

**Comment by liuxuan30** [comment]
you should use source code and check catalyst. But I do not plan to encourage to do it, as we have mac version.

**Comment by Planet30** [comment]
Hello, I have exactly the same problem.

I copied the Charts.xcodeproj into my project in Xcode, registered the framework and can run the app on the simulator and physically on the iPad.

But not with Mac Catalyst. I get the same error as stated above by the original post.

Sorry, I do not understand your comment "use source code"? Do I have to generate swift files rather than the framework?

From what I understood, the Mac Catalyst should use the same Frameworks as iOS, correct? Sorry, I am new to this and a little bit lost.

**Comment by nsands** [comment]
Same issue here.  No action on this after 2.5 years?

Mac Catalyst is a big game changer for a lot of application developers.  Can we get this to work correctly for this framework, somehow?
