### ISSUE TITLE
Two markers at the same X Axis in LineChart

### ISSUE THREAD

**Issue by wongzigii** [danielgindi/Charts#4559]
Is there way to show two markers by the x axis at the same time?
For now, the `chartValueSelected` delegate method only return the nearest entry of my tapping gesture.

![image](https://user-images.githubusercontent.com/7384288/105443430-a2c3ce80-5ca6-11eb-9923-de4b673f78d4.png)

**Comment by wongzigii** [comment]
@objc optional func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight)

Shouldn't the highlight parameter of this method is an array?

**Comment by notkevinvu** [comment]
For anyone wondering how you can configure this, my solution is essentially to pass some data to the marker corresponding to your data sets. 

Let's say what we want to do is to have a line chart with multiple lines (i.e. data sets) and we want to be able to tap the chart and have it highlight/mark the lines at the given x value. Let's say you already have a custom marker class for the chart. `class CustomMarker: MarkerImage {}` (see this stack overflow thread for more information: https://stackoverflow.com/questions/34981568/how-can-i-add-a-marker-on-ios-charts)

In order to create a marker at each line on the chart, we can use the delegate method `chartValueSelected(_ chartView:...)` to create highlights for each data set and highlight the values.

```swift
var highlights: [Highlight] = []
let dataSetCount = chartView.data?.dataSetCount ?? 0

for i in 0 ..< dataSetCount {
    let highlight = Highlight(x: entry.x, y: Double.nan, dataSetIndex: i)
    highlights.append(highlight)
}

chartView.highlightValues(highlights)
```

If we want to customize the marker we show at each data set/line, we can override the `refreshContent(entry:..., highlight:..)` method to adjust the marker for the corresponding data set via the `highlight.dataSetIndex` property. 

For this example, when adding data sets to my chart view, I would also add corresponding properties to my marker.

```swift
public func addDataSetToChart(withChartEntries chartEntries: [ChartDataEntry]) {
    var dataSetColor: UIColor
    // customize logic for color based on what data set we add
    // e.g. if someCondition { dataSetColor = .red }
    let dataSet = LineChartDataSet(entries: chartEntries)
    chartView.data?.addDataSet(dataSet)
    customMarker.addColorForDataSet(color: dataSetColor)
}
```

Then we update the color in our custom marker class:

```swift
var dataSetColors: [UIColor] = []

override func refreshContent(entry: ChartDataEntry, highlight: Highlight) {
    color = dataSetColors[highlight.dataSetIndex]
}
```

This should result in different color markers for each line being highlighted in the chart. This can be adjusted to show different data in the marker (i.e. if you have text in the marker, you can update the text in `refreshContent()`)

**Comment by VikBob** [comment]
您好， 请教下 图标中有两条折线图， 然后拖动uislider 显示选中两条线的交叉点，该如何实现。
拖动的时候两个圆圈跟着折线图移动。
![image](https://github.com/danielgindi/Charts/assets/10754795/44673e25-f6de-4989-8c3e-b28ea9be12fe)
