### ISSUE TITLE
Release 4.0 availability through CocoaPods

### ISSUE THREAD

**Issue by matantech** [danielgindi/Charts#4776]
Hi, 
I'm facing the issue reported at #4049 and as far as I understand the available fix already merged and exist at version 4.0.
When trying to install it through CocoaPods I got the Algorithm error #4611 which tells that the only way of solving that issue is installing the Charts through SPM. I'm already using CocoaPods at my project and a bit scared that mixing both of them will not be a good idea. When will the V4.0 be available through CocoaPods?

**Comment by smidaharoun** [comment]
Any updates on this ? Is there a reason why the versions >= 4.0 are not available on cocoapods ?

**Comment by smidaharoun** [comment]
Ok here is what I found #4611 & #4646  : 
`4.0.0 does not support the pods, only use Swift Package. Because the latest version depend on Algorithms, Algorithms is Apple's open source library, unfortunately, Algorithms can only be installed through Swift Package.`

So for now the answer is no, you must migrate to SPM if you want the new version

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods
