### ISSUE TITLE
Hello, can you consider supporting flutter?

### ISSUE THREAD

**Issue by codertiany** [danielgindi/Charts#4833]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag [`ios-charts`.](https://stackoverflow.com/questions/tagged/ios-charts)
>
> Please remove this line and everything above it before submitting.

* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:**
**Swift version:**
**Platform(s) running Charts:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by liuxuan30** [comment]
not really. This project is now more like in a maintenance mode since lack of man powers. Each major contributor is busy with their work & life. For example I myself have to work 10 hours a day and couldn't find a time slot to sit down and fix a few bugs. 

Since Apple is releasing Swift Charts in WWDC2022, I would assume to transfer to that, unless you have other demand that only this library can fulfill.
