### ISSUE TITLE
CombinedChartView  bubbleData size not working

### ISSUE THREAD

**Issue by jasonxiaochao** [danielgindi/Charts#692]
yBubbleVals.append(BubbleChartDataEntry(xIndex: i, value: 10, size: 10))

the size is not working  ,
thie bubble width always equals the bar width

**Comment by liuxuan30** [comment]
I am not sure why, but changing below code in bubble chart renderer `drawDataSet` func would make bubbles different size:
```swift
//            let shapeSize = getShapeSize(entrySize: entry.size, maxSize: dataSet.maxSize, reference: referenceSize)
            let shapeSize = entry.size // directly use
            let shapeHalf = shapeSize / 2.0
```
So seems the reason is getShapeSize. I print out a few, seems they are quite close, becaue the value is already in pixel
```
(lldb) po shapeSize
23.3481437335035

(lldb) po shapeSize
26.2410481770833

(lldb) po shapeSize
24.8367512492309

(lldb) po shapeSize
21.7579277272562
```
I would not say it's equals to bar width, but the difference is small. 
@petester42 do you have idea?

**Comment by danielgindi** [comment]
The size was always being normalized against the max size in the dataset.
You can now turn it off by using `normalizeSizeEnabled = false`, on `master`
