### ISSUE TITLE
ChartMaker work wrong in a Combined Chart

### ISSUE THREAD

**Issue by AidenWK** [danielgindi/Charts#737]
###  Summary:
ChartMaker work wrong in a Combined Chart. 
CombinedChartData got a line data , a bar data, the line data highlightEnabled  is NO , the bar data highlightEnabled is YES,  then set a ChartMaker to Combined Chart. The maker is always reveal the line data value, even the bar data is selected in this situation.

### Expected Results:
 The maker is reveal the line data value when the line data selected(highlighted),
reveal the bar data value when the bar data selected(highlighted).

### Steps to Reproduce:
In the example project, ChartDemo

1) In the CombinedChartViewController  add code in func viewDidLoad
 ``BalloonMarker *marker = [[BalloonMarker alloc] initWithColor:[UIColor colorWithWhite:180/255. alpha:1.0] font:[UIFont systemFontOfSize:12.0] insets: UIEdgeInsetsMake(8.0, 8.0, 20.0, 8.0)];
    marker.minimumSize = CGSizeMake(80.f, 40.f);
    _chartView.marker = marker;``
2)  add code in func -(LineChartData *)generateLineData
``set.highlightEnabled = NO;``
3) add code in func -(BarChartData *)generateBarData
``set.highlightEnabled = YES;``
4) build and run

### Bug in Code
when I debug for this, I found the call stack :
tapGestureRecognized in BarLineChartViewBase.swift ->
``getHighlightByTouchPoint`` in  BarLineChartViewBase.swift ->
``getHighlight`` in ChartHighlighter.swift ->
``getDataSetIndex`` in ChartHighlighter.swift ->

i think  there is some wrong in code below

``let dataSetIndex = ChartUtils.closestDataSetIndex(valsAtIndex, value: y, axis: axis)``
if a chart not a combine chart , this func result  dataSetIndex is right , but In a Combined Chart , dataSetIndex  is wrong ,  

can anybody recheck this

ps:  in my Objective-c project, debug swift is so difficult , any good skills?

**Comment by liuxuan30** [comment]
First of all, debugging swift is still using LLDB, so nothing changed. I always add break points in swift code directly, it breaks fine.

For the chart marker issue, I think I notice this in my grouped bar support PR for combined chart. It has some order preference maybe.. anyway, you are welcome to debug and file a PR to fix it. Or I will check it when I get home.. after tomorrow. Spring festival is coming :)

**Comment by PreechaS** [comment]
I got the same problem when using Combined Chart to show Candle Chart and Line Chart together.
The Marker displays only data from Candle Chart, not from Line Chart. This project works well with previous version of iOS Charts and XCODE 6.

I hope someone will find the solution. (My knowledge of Objective-C is very bad so I can't debug it)

**Comment by liuxuan30** [comment]
sorry.. I am fully occupied recently to have some spare time dig into this.

**Comment by SvenMuc** [comment]
I just updated from Charts v2.2.4 to v2.2.5. With the latest version I got same problems in my App.

Unfortunately my debugger does not work correctly with Charts. I don't know why but I cannot get any attribute values. Outside of Charts the debugger works almost fine for Swift.

Charts crashed at the following line:

`let data = dataObjects[highlight.dataIndex]` in the function `public override func getEntryForHighlight(highlight: ChartHighlight) -> ChartDataEntry?`
It seems that the index `highlight.dataIndex`is out of range.

Any ideas?

**Comment by SvenMuc** [comment]
Today the debugger works again for Swift. Seems to be a bit unstable. Nevertheless, I identified an negative dataIndex value (-1) as the root cause for the crash. See also attached images.

**Source Code**
![bildschirmfoto 2016-06-20 um 07 52 03](https://cloud.githubusercontent.com/assets/13385716/16184437/9df02de6-36bc-11e6-910e-37b4f61ebaab.png)

**Debug Data**
![bildschirmfoto 2016-06-20 um 07 51 13](https://cloud.githubusercontent.com/assets/13385716/16184449/b742fd50-36bc-11e6-9904-9f24e6e0cc3d.png)

**Stack**
![bildschirmfoto 2016-06-20 um 07 58 14](https://cloud.githubusercontent.com/assets/13385716/16184460/d014f5cc-36bc-11e6-949f-3a60e9cf94d1.png)

Maybe this information helps for further debugging. I tried a bit but didn't understand the code so far.

**Comment by liuxuan30** [comment]
This seems a new feature called highlight all introduces  this all -1 highlight object

**Comment by SvenMuc** [comment]
No I did not enabled it explicitly in the code. I just took my existing code and updated to latest Charts version. It seems that the default of 'highlightFullBarEnabled' in the `CombinedChartView` is true. 

In case I explicitly initialize it with false I get an index offset for the `dataSetIndex`. In the following image I selected a point in the line chart view. In the function call `func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: ChartHighlight)` I highlight the same point in the `CombinedChartView`. But as you can see in the image below a `dataSetIndex = 0` highlights the wrong data set. Maybe there is somehow a bug in the index calculation or the new feature you mentioned.
I double checked the data set index in the `CombinedChartView`The red line has the index 1.

![bildschirmfoto 2016-06-22 um 21 12 08](https://cloud.githubusercontent.com/assets/13385716/16280162/9c23f836-38be-11e6-9e0e-a93c6e25f89a.png)

**Comment by liuxuan30** [comment]
I remember the combined chart has changed its logic about how to get the data set index. Is this related? e.g. in old time, it counts the index in the whole data scope, while in new logic, it calculates the index in the specific chart data? like in bar data. I am not sure if I am corrrect

**Comment by jeroenleenarts** [comment]
Running into this issue too. It appears there is no logic in the ```CombinedChartView``` to correctly handle the ```highlightFullBarEnabled``` effects just yet.

**Comment by liuxuan30** [comment]
Alright, I finally got some time looking into this.. 
Yes, CombinedChartView did set `self.highlightFullBarEnabled = true` by default, and ChartMarker will crash for sure. Because those -1 values.
For now, please set self.highlightFullBarEnabled = false to avoid the crash. I am trying to find a fix

**Comment by liuxuan30** [comment]
however, this is actually two issues, one is the crash, the second is the marker is not drawing at the correct position. I will use #1185 for the crash.

**Comment by liuxuan30** [comment]
@SvenMuc for your issue with 2.2.5 release, I don't think dataSetIndex = 0 is a bug here.
Start with 2.2.5, the combined chart highlight object will give a description like:
```
  ▿ Some : Highlight, xIndex: 5, dataIndex (combined charts): 2,dataSetIndex: 0, stackIndex (only stacked barentry): -1, value: 46.0
```
here, the `dataIndex` means the data index in combined chart data (or data itself is always 0)
and `dataSetIndex` means the index in the specific data, not combined chart data itself, it means the data at index 2 in combined chart data.

So in order to get the correct data set here, it's like dataAtIndex(2).dataSetAtIndex(0)

**Comment by liuxuan30** [comment]
@danielgindi I think we got a major problem with `drawMarkers()` when `highlightFullBarEnabled = true`.

Some of my questions and issues trying to fix:
1. `highlightFullBarEnabled` gives me the hint that it's all about bars, however, it looks like all BarLineChartViewBased chart (line, bar, scatter) supports this feature, so it's kind of confusing, it's more like `highlightAllEnabled` rather than just bars... we probably need to rename it

2. Currently, if `highlightFullBarEnabled` is true, all `drawMarkers()` will crash because the dataSetIndex = -1. I am not sure how we want to handle this case for markers. Right now, markers are bound to highlight objects, so we don't know what dataSet to highlight, not even mentioning the combined chart.

So in order to fix, what I see is we could recalculate the highlight separately for markers, getting the closest xIndex, dataIndex, dataSetIndex etc. to make it show the correct space. However, this will introduce more loops to calculate the position again, kind of performance drop here. 

Another way is that, once we see `highlightFullBarEnabled` is true, we do not calculate the -1 highlight, instead, in renderer, we push all the data sets with same xIndex into highlight array before highlighting takes place, so highlight object still refers to the closest entry, we just hack how it looks, this will not introducing recalcuation, but this will make the chartValueSelected return wrong highlight info (highlight all vs. individual highlight)

In pseudo code, it looks like:
```swift
func beforeDrawHighlighted(indices: [ChartHighlight])
        highlights = [ChartHighlight]()
    if highlightall { 
        for set in dataSets {
             h = highlightFromDataSet(set)
             highlights.append(h)
        }
     } else {
        highlights = indices
    drawHighlighted(highlights)
}
```

@danielgindi what do you think and how about other guys watching this issues? Any ideas? Is the performance drop acceptable etc.?

**Comment by danielgindi** [comment]
Solved in Charts 3.0 (v3 branch)

**Comment by royherma** [comment]
Same issue with @SvenMuc...

> 
> let data = dataObjects[highlight.dataIndex] in the function public override func getEntryForHighlight(highlight: ChartHighlight) -> ChartDataEntry?
> It seems that the index highlight.dataIndexis out of range

I'm on Charts 3.0.5, any idea if this is really fixed as @danielgindi mentioend?

Using a CombinedChart with `self.candleStickChartView.highlightFullBarEnabled = false`

**Comment by liuxuan30** [comment]
it's a very old issue for this. Are you able to use it and test? If you found issues, open an new one with details.
