### ISSUE TITLE
Missing a piece of data to the left

### ISSUE THREAD

**Issue by oxodpavel** [danielgindi/Charts#785]
Hi!

When scrolling the graph horizontally, it sometimes misses a piece of line to the left of the most left point of the view box. That is, a piece of line between Y axis and the first point on the graph

I do not if this can be assumed as an issue or a default behavior or I can configure it from code, but sometimes there may be a misunderstanding on whether there is some data to the left of not.

![test_app](https://cloud.githubusercontent.com/assets/17591717/13458917/3ce3c10c-e081-11e5-8939-8d9ea3da26c8.jpg)

**Comment by liuxuan30** [comment]
your screenshot sesm not reflect the problem, could you mark where is missing? or a comparision

**Comment by oxodpavel** [comment]
Here is another screenshot with marked area. To the left of the point there is some preceding data, but the graph line piece is missed. And when you move horizontal axis it sometimes becomes visible or invisible
![app](https://cloud.githubusercontent.com/assets/17591717/13498054/5e41600a-e169-11e5-895f-e13a86b0e980.jpg)

**Comment by danielgindi** [comment]
@PhilJay  can you take a look at the PR?

**Comment by PhilJay** [comment]
If the PR introduces correct behaviour or not depends on the implementation of the `round(...)` method.
What we basically want is to display the lowest VISIBLE index.

This means if the edge of the chart is at 0.01 or 1, the lowest visible x-index returned by the method should be 1.

According to [this](http://stackoverflow.com/a/26351144/1590502) post, the round method does is round up for everything >= 0.5
This would introduce incorrect behaviour for values between 0.01 and 0.49, because those values would be rounded down but actually should be rounded up.

I think the `ceil(...)` method should be used for rounding.
