### ISSUE TITLE
Radar Chart- Setting the maximum Y-Axis value.

### ISSUE THREAD

**Issue by psuedonovicecoder** [danielgindi/Charts#994]
`radarChart.yAxis.customAxisMin = min(0.0, radarChart.data!.yMin - 1.0)`
`radarChart.yAxis.customAxisMax = max(100.0, radarChart.data!.yMax + 1.0)`

I used these line of code to set the maximum Y-axis values yesterday but today the return a "Value of type 'ChartYAxis' has no member 'customAxisMin/Max'"
Did the code change from yesterday to today?
What am i doing wrong?

**Comment by danielgindi** [comment]
You have to read release notes to see how releases affect the code...
Specifically - customAxisMin was a non-compatible naming to the Android equivalent, due to some ambiguous naming. It was fixed, the old APIs were deprecated, and a new and better API was introduced cross-platform. Finally `customAxisMin` was removed.

So please move to `axisMinValue`.
